name: CI
on: [push]

jobs:
  ci:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install Yarn dependencies
        run: yarn install

      - name: Run prettier
        run: yarn prettier
